import 'package:flutter/foundation.dart';
import '../provider/soup.dart';

class Soups with ChangeNotifier {
  List<Soup> _soupItems = [
    Soup(
      id: 's1',
      description: 'A tastey local nigerian dish soup that draws',
      duration: 45,
      imageUrl: 'assets/images/bitterleaf-soup.jpg',
      ingredients: [
        'Washed and squeezed bitterleaf – A handful',
        '10 small corms Cocoyam',
        '3 cooking spoons Red Palm Oil',
        'Assorted Beef: Includes best cut, shaki (cow tripe)',
        'Assorted Fish: Dry Fish and Stock Fish',
        'Pepper, salt and ground crayfish (to taste)',
        ' 3 stock cubes',
        '1 teaspoon Ogiri Igbo (traditional seasoning)',
      ],
      origin: 'Igbo (Eastern)',
      steps: [
        'Boil the shaki (cow tripe), stock fish and dry fish in 1 litre of water till they are well done.',
        'Wash the beef and add to the pot of shaki etc. and continue cooking. When the meat is done, add 3 cubes of Maggi/Knorr and cook for 5 minutes.',
        'Add pepper, ground crayfish, bitter leaves and cook for 10 minutes. Then add the cocoyam paste (in small lumps) and the palm oil then go to step 5.',
        'Cover the pot and leave to cook on high heat till all the cocoyam lumps have dissolved. You can add more water if you feel that the soup is too thick',
        'Add salt to taste and the soup is ready',
      ],
      title: 'Bitter leaf',
    ),
    Soup(
      id: 's2',
      description: '',
      duration: 30,
      imageUrl: 'assets/images/diaspora-vegetable-soup.jpg',
      ingredients: [
        '2 kg frozen spinach',
        '250g lamb’s lettuce',
        '2kg Assorted meat',
        'Stock fish',
        '4 tablespoons ground crayfish',
        '6 small Knorr cubes',
        'Sweet pepper (for colour)',
        'Habanero pepper (to your taste)',
        '2 big bulbs of onion',
        '1½ cups of red palm oil',
        'Salt (to taste)',
      ],
      origin: '',
      steps: [
        'Cook the meats and stock fish with the seasoning cubes and half of the chopped onions.',
        'When done, remove all the meat and fish and set aside.',
        'De-bone and separate the stockfish into small pieces.',
        'Make sure the stock is as little as possible, if not, boil it down first before continuing.',
        'Set the stock on the stove, add palm oil, crayfish, the remaining chopped onions. Cover and cok for about 7 minutes to allow the palm oil integrate into the soup.',
        'Add the peppers, the lambs lettuce, the meats and fish.',
        'Cover and once it boils again, add the spinach.',
        'Cover and once it boils again, stir very well and add salt if necessary.',
      ],
      title: 'Vegetable',
    ),
    Soup(
      id: 's12',
      description: '',
      duration: 40,
      imageUrl: 'assets/images/okra-soup.png',
      ingredients: [
        '5 cups (250g) Okra',
        '3 cooking spoons red palm oil',
        'Beef: Best cut',
        ' Shaki (Cow Tripe) (Optional)',
        'Fish: Iced Fish (Mackerel/Titus), Dry Fish, Stock Fish',
        '1 handful crayfish',
        'Pepper and Salt (to taste)',
        'Onions (optional)',
        ' Vegetable: Nigerian pumpkin leaves or spinach (fresh or frozen)',
        '3 stock/boullion cubes',
      ],
      origin: '',
      steps: [
        'If you will use shaki (cow tripe) for the soup, wash and boil till it is done. Add water sparingly because this soup needs to be thick. Add the soaked stockfish and dry fish to the cooked shaki. ',
        'Add the beef, onions and stock cubes and cook till done. Then add the iced fish and cook till done.',
        '''Pour red palm oil in another pot and heat the pot to dissolve the oil if it is congealed. Add the diced okra and start frying to kick-start the drawing process, add some meat stock from time to time till you notice the okra start to draw.
       This process should take a maximum of 5 mins to avoid over-cooking the okra.''',
        'Now add the vegetable and stir well. Add all the meat and fish, crayfish, pepper and salt to taste. Then stir well.',
        'Cover the cooking pot and leave to simmer and it is ready to be served.',
      ],
      title: 'Okra ',
    ),
    Soup(
      id: 's3',
      description: '',
      duration: 30,
      imageUrl: 'assets/images/ofe-nsala.jpg',
      ingredients: [
        '1 big Catfish',
        '8 small pieces white yam',
        '5 Utazi leaves',
        '2 small seasoning cubes',
        'Small piece of ogiri okpei',
        'A handful crayfish',
        'Habanero pepper (to taste)',
        'Salt (if necessary)',
      ],
      origin: 'Igbo (Eastern)',
      steps: [
        'Add the seasoning cubes (crushed) to the pot of fish.',
        'Add the pieces of yam.',
        'Pour water to cover everything and start cooking.',
        'When the yam is soft and moist, bring them out and place in a mortar.',
        'Add the pounded crayfish, pepper, ogiri okpei and utazi into the pot of fish and continue cooking.',
        'Pound the cooked yam in a mortar till smooth and stretchy.',
        'Add the yam into the pot of Ofe Nsala in small lumps, cover and continue cooking.',
        'Once the yam dissolves and thickens the soup, it is done.',
        'Add salt if necessary, stir very well and that’s it!',
      ],
      title: 'Ofe-nsala',
    ),
    Soup(
      id: 's4',
      description: '',
      duration: 50,
      imageUrl: 'assets/images/ogbono-soup1.jpg',
      ingredients: [
        '8 tablespoons ground Ogbono',
        'Meat',
        'Dry cat fish',
        '3 cooking spoons red palm oil',
        '2 handfuls crayfish',
        '1 flat round ogiri okpei (Iru, Locust bean)',
        'Habanero pepper (ose oyibo, atarodo)',
        '1 onion',
        ' 2 big seasoning cubes',
        ' Ugu (Nigerian pumpkin leaves)',
        'Salt (to your taste)',
      ],
      origin: 'Unknown',
      steps: [
        'Cook the assorted meat with the seasoning cubes and onion. When the meat is done, turn off the heat, remove the chunks of onion then take out the meat from the beef stock',
        'Add the ground ogbono, spreading over the meat stock as you add. Then stir very well with a slotted spoon to ensure that they mix with the beef stock without lumps.',
        '''Stir the soup very often as you cook so it does not burn.
After 15 minutes, add the crayfish and ogiri okpei blend, habanero pepper, deboned dry cat fish, salt and palm oil in no particular order and continue cooking. Remember to stir often''',
        'After 5 minutes (a total of 20 minutes of cooking), add the remaining ingredients:You need to cook Ogbono for at least 20 minutes for the delicious taste and flavour to come out',
        'Cover the pot and at the first sign of it boiling again, it\'s done!',
      ],
      title: 'Ogbono',
    ),
    Soup(
      id: 's5',
      description: '',
      duration: 60,
      imageUrl: 'assets/images/afang-soup.png',
      ingredients: [
        ' 400g sliced Okazi/Afang leaves | about 4 handfuls',
        '250g Water leaves',
        '20 to 25 cl red palm oil (about 1 drink glass)',
        'Beef, Kanda and Dry fish',
        '2 tablespoons ground crayfish',
        'Pepper and salt (to taste)',
        ' 2 stock cubes',
      ],
      origin: 'Efik(Akwa-Ibom & Cross-River)',
      steps: [
        'Boil the beef and Kanda with the diced onions and stock cubes in a very small quantity of water. When done, add the dry fish and cook for about 5 more minutes. ',
        'Now add the palm oil, crayfish and pepper. ',
        'Once it starts boiling, add the afang (okazi) leaves, water leaves and periwinkle. When the okazi leaves have softened and the water has dried up a bit',
        ' Add salt to taste and leave to simmer for about 5 minutes. The Afang soup is ready',
      ],
      title: 'Afang',
    ),
    Soup(
      id: 's6',
      description: '',
      duration: 55,
      imageUrl: 'assets/images/kale-efo-riro.jpg',
      ingredients: [
        '400g Kale Leaves , Washed and Chopped',
        '4 Red Bell Peppers (Tatatshe)',
        '2-3 Scotch Bonnet  (Ata rodo)',
        '1/2 Cup Palm oil',
        '1 Cup Meat or Chicken Stock',
        '2 Medium Size Red Onions',
        '1kg Boiled Assorted Meats of your choice (Shaki, Kpomo, cow leg, smoked turkey or beef are ideal)',
        'Dried Stockfish, Shredded (panla)',
        'Smoked Cat fish, Shredded',
        '3 Tablespoons Locust beans (Iru)',
        '1/2 Cup Raw/Smoked Prawns(optional)',
        '2 Knorr Cubes',
        '3 Tablespoons Ground Crayfish',
        'Salt to taste',
      ],
      origin: 'Yoruba(Western)',
      steps: [
        'Blend the Scotch bonnets, Bell peppers and an Onion coarsely and set aside then chop the second Onion and set aside.',
        'Place a medium size pot on medium heat. Add the Palm oil, leave to heat up for 2 minutes then add the Chopped onions, sauté till fragrant. Then add the Locust Beans, fry to release the flavour for another minute…',
        'Then add half of the Crayfish, fry for a minute…',
        'Now add the blended Pepper, two Knorr cubes and Salt to taste, leave to boil for 15-20 minutes thereabout or until the pepper dries out and the size reduces by almost half..',
        'The pepper at this time needs to be a thickish consistency and the oil should have settled on the top…',
        'If the consistency is too thick, add a bit of the meat stock/ chicken stock, if you haven’t got stock, just add water, be careful not to add too much. Just one cup should do.',
        'If you added Stock, allow to boil for 2-3 minutes to combine, then add the assorted meats, stir and combine. Leave to cook for 8-10 minutes…',
        'Then add the Prawns, the rest of the Crayfish, shredded Stockfish and Smoked Catfish…',
        'Combine and taste, adjust seasoning if required. Leave to cook for a further 5 minutes…',
        'Now add the Chopped Kale leaves, combine thoroughly. Leave to cook for 5 minutes…',
        'Switch off the heat at this time, then leave to simmer with the residual heat for a further 2 minutes. Your Kale Efo Riro is ready…',
      ],
      title: 'Efo Riro',
    ),
    Soup(
      id: 's7',
      description: '',
      duration: 45,
      imageUrl: 'assets/images/gbegiri-soup.jpg',
      ingredients: [
        '150g Black Eyed or Brown Beans',
        '1 small smoked Mackerel/Titus',
        '1 tablespoon ground crayfish',
        '1 big stock cube',
        ' 1 cooking spoon palm oil',
        'Pepper and salt (to taste)',
      ],
      origin: 'Yoruba(Western)',
      steps: [
        'Put the peeled and soaked beans into a sizeable pot. Pour water to cover the beans and start cooking at medium heat.',
        'While the beans is cooking, prepare the Ewedu Soup which is used to eat the Gbegiri Soup.',
        'Cook the beans till they become so soft that it practically melts when you mash it with your fingers. This takes about 1 hour. You will need to top up the water from time to time but make sure the water is always at the same level as the beans. This ensures that you have just the right amount of water in the soup when the beans is done.',
        'When the beans is well done and soft, blend it. It is not advisable to blend hot food in blenders with plastic jugs so if your blender has a plastic jug, seive the soft beans with a sieve that has a mire mesh.',
        'Pour the beans into a pot and set back on the stove, add the smoked fish, salt, pepper, crayfish, stock cube and palm oil.',
        'Cover the pot and cook at low heat for about 5 minutes or till the oil blends with the rest of the ingredients. This is when the oil changes from red to yellow.',
        'Stir from time to time so it does not burn,and its ready!!',
      ],
      title: 'Gbegiri',
    ),
    Soup(
      id: 's8',
      description: '',
      duration: 45,
      imageUrl: 'assets/images/banga-soup.jpg',
      ingredients: [
        '1 kg Palm Fruits or 800g tinned Palm Fruit Concentrate',
        'Beef',
        'Dry Fish',
        'Vegetable: Scent Leaves for Ofe Akwu or dried and crushed bitterleaves for Delta-style Banga Soup',
        '2 medium onions',
        '2 tablespoons ground crayfish',
        'Salt and Chilli Pepper (to taste)',
        'Ogiri Okpei (Iru)',
        '1-2 big stock cubes',
      ],
      origin: 'Niger Delta',
      steps: [
        '''Set the pot of palm fruit extract on the stove and start cooking at high heat. Leave to boil till you notice come red oil at the surface of the Banga Stew. 
      If you think that the Banga Soup is watery, cook till the soup has thickened to the consistency you like for your stews.''',
        'Now, add the beef, dry fish and stock, the onions, crayfish and pepper and leave to boil very well.',
        'Add the scent leaves or other vegetable and salt to taste. Leave to simmer for about 2 mins.The Banga Soup is done. ',
      ],
      title: 'Banga',
    ),
    Soup(
      id: 's9',
      description: '',
      duration: 35,
      imageUrl: 'assets/images/egusi-soup.jpg',
      ingredients: [
        '4½ cups (600g) Egusi (Melon) seeds',
        '2 cooking spoons red palm oil',
        'Beef: Best cut and Shaki (cow tripe)',
        ' Fish: Dry Fish and Stock Fish',
        '3 tablespoons ground crayfish',
        'Pepper and Salt (to taste)',
        'Vegetable: Nigerian pumpkin leaves, spinach or bitter leaves',
        '3 small stock cubes',
        ' 1 Ogiri Okpei (traditional locust bean seasoning: optional)',
      ],
      origin: 'Unknown',
      steps: [
        'Boil the shaki, stock fish and dry fish in 1 litre of water with the stock cubes till they are well done. First sign of a done shaki is that the cuts will start curling on itself.',
        'Wash the beef to be used for the soup, add it to the pot and cook on medium heat till done.',
        'As soon as the shaki, fish and meat are done, add crayfish and pepper, stir and remove all the meat from the stock (water used in cooking the meat and fish) and place in a different pot or plate.',
        'Add the ground egusi to the stock and stir. If the stock from cooking your meat and fish is not enough to give you a medium consistency, add some water to get the consistency of evaporated milk or a bit thicker. It will not be as smooth as evaporated milk though.',
        'Cover and cook till the egusi cakes. Stir and add a little bit more water. watch it closely so that it does not burn.',
        'Repeat step 3, adding only a small quantity of water at a time. After about 25 minutes, you will notice the clear egusi oil coming to the surface of the soup.',
        'Add the red palm oil and bitter leaves (if it is your choice of vegetable), pepper and salt to taste and cook for about 7 minutes.',
      ],
      title: 'Egusi',
    ),
    Soup(
      id: 's10',
      description: '',
      duration: 45,
      imageUrl: 'assets/images/catfish-pepper-soup.jpg',
      ingredients: [
        '500g Cat Fish',
        ' 4 Ehu or Ariwo or Calabash Nutmeg seeds',
        'Habanero Pepper or chilli pepper (to taste)',
        'A few scent leaves',
        '2 medium onions',
        'Salt (to taste)',
        '2 big stock cubes',
      ],
      origin: 'Joint',
      steps: [
        'Place the pieces of fish in a pot and pour water to just cover the fish, add the stock cubes and bring to the boil.',
        'Once it starts to boil add the ground ehu, onions, habanero pepper and scent leaves and continue cooking.',
        'Once the catfish is done, add salt to taste and leave to simmer for about 5 minutes and it\'s ready!',
      ],
      title: 'Point & Kill',
    ),
    Soup(
      id: 's11',
      description: '',
      duration: 35,
      imageUrl: 'assets/images/owho-soup.jpg',
      ingredients: [
        'Assorted meat and fish:Bee ,Cow Skin (ponmo) ,Cow tripe ,Snails, Dry fish, Stock fish',
        'Palm oil',
        '2 teaspoons powdered edible potash (akanwu, kaun, keun)',
        '3 tablespoons ground crayfish',
        '1 cup garri',
        'Hot and spicy pepper (to taste)',
        '2 stock cubes',
      ],
      origin: 'Urhobo',
      steps: [
        'Soak the dry fish to soften.',
        'Mix the potash with a little amount of water and set aside.',
        'Clean, debone and separate the dry fish into medium pieces.',
        'Pour the palm oil in a small container, gently decant the potash water into the palm oil while stirring at the same time till the palm oil turns yellow and becomes thick.',
        'Cook the meats and stockfish with the seasoning cubes till soft.',
        'Blend the garri with a dry mill then mix it with some meat and fish stock to get a soft dough. See the video below.',
        'Add the dry fish, crayfish and pepper to pot, cover and continue cooking.',
        'After about 7 minutes, add the palm oil mix and scoop small lumps of the garri dough into the pot and continue cooking. Do not cover it from the point onwards because it will boil over due to the edible potash in the palm oil.',
        'It is done when the lumps of garri have disolved and the soup is no longer foaming. If you get the consistency you like for your soups before the garri lumps completely dissolve, remove the excess lumps.',
        'Stir very well and take it off the stove.',
      ],
      title: 'Owho',
    ),
  ];

  List<Soup> get soupItems {
    return [..._soupItems];
  }

  List<Soup> get showFavourites {
    return _soupItems.where((soup) => soup.isFavourite).toList();
  }
}
